### ISSUE TITLE
模型生成回复失败

### ISSUE THREAD

**Issue by qingfenga6** [xiangsx/wechatgpt#2]
模型生成回复失败是哪一步出问题了呀

**Comment by xiangsx** [comment]
> 模型生成回复失败是哪一步出问题了呀

科学上网了吗

**Comment by xiangsx** [comment]
> > 模型生成回复失败是哪一步出问题了呀
> 
> 科学上网了吗
你有代理的话，下午我加个代理的配置

**Comment by xiangsx** [comment]
最新版本 已支持代理
