### ISSUE TITLE
大佬能提供一个openai的key吗 

### ISSUE THREAD

**Issue by ummmmer** [xiangsx/wechatgpt#5]

**Comment by xiangsx** [comment]
> 

咋可能给你key  都是有额度限制的

**Comment by ummmmer** [comment]
> 

好吧..我看你文章内说联系你 给一个。 他们那些免费端口是怎么搞的。公众号和一些群聊里的

**Comment by xiangsx** [comment]
> > 
> 
> 好吧..我看你文章内说联系你 给一个。 他们那些免费端口是怎么搞的。公众号和一些群聊里的

先加我qq吧

**Comment by ummmmer** [comment]
> 
ok
