### ISSUE TITLE
启动docker 报错c_wechatgpt  | Error: Cannot find module './config.js'

### ISSUE THREAD

**Issue by vc815** [xiangsx/wechatgpt#6]
你好  c_wechatgpt  | Error: Cannot find module './config.js'按照步骤都操作了  但一直报这个错误   怎么解决呢 ？谢谢

**Comment by xiangsx** [comment]
![image](https://user-images.githubusercontent.com/29322721/232958334-e2f41423-7372-49e1-a1c3-2fb030e8e42b.png)

这个步骤做了吗
